/**
 * Unit Tests Results Page
 * 
 * Displays unit test results from Vitest
 * Shows pass/fail counts, test duration, and individual test files
 */

import React from "react";
import { CheckCircle, XCircle, Clock, FileCode, Layers, Wrench, RefreshCw } from "lucide-react";
import { WexCard, WexBadge, WexProgress, WexTabs, WexButton } from "@/components/wex";
import { Section } from "@/docs/components/Section";
import { CodeBlock } from "@/docs/components/CodeBlock";

// Import test summary (generated by scripts/generate-unit-test-report.js)
import testSummary from "@/docs/registry/unit-test-summary.json";

interface CategoryData {
  passed: number;
  failed: number;
  total: number;
  files: Array<{
    name: string;
    path: string;
    status: string;
    passed: number;
    failed: number;
    duration: number;
  }>;
}

interface TestSummary {
  _meta: {
    generatedAt: string;
    testRunner: string;
    totalDuration: number;
  };
  totals: {
    suites: number;
    tests: number;
    passed: number;
    failed: number;
    pending: number;
    passRate: number;
  };
  categories: {
    components: CategoryData;
    utils: CategoryData;
    hooks: CategoryData;
  };
  failures: Array<{
    file: string;
    test: string;
    message: string;
  }>;
}

const data = testSummary as TestSummary;

function formatDuration(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function StatusBadge({ status }: { status: string }) {
  if (status === "passed") {
    return (
      <WexBadge variant="outline" className="bg-success/10 text-success border-success/30">
        <CheckCircle className="h-3 w-3 mr-1" />
        Passed
      </WexBadge>
    );
  }
  return (
    <WexBadge variant="outline" className="bg-destructive/10 text-destructive border-destructive/30">
      <XCircle className="h-3 w-3 mr-1" />
      Failed
    </WexBadge>
  );
}

function CategoryCard({ 
  title, 
  icon: Icon, 
  category 
}: { 
  title: string; 
  icon: React.ElementType; 
  category: CategoryData;
}) {
  const passRate = category.total > 0 
    ? Math.round((category.passed / category.total) * 100) 
    : 0;

  return (
    <WexCard className="overflow-hidden">
      <WexCard.Header className="pb-3">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-lg bg-primary/10">
            <Icon className="h-4 w-4 text-primary" />
          </div>
          <WexCard.Title className="text-base">{title}</WexCard.Title>
        </div>
      </WexCard.Header>
      <WexCard.Content className="space-y-3">
        <div className="flex items-baseline justify-between">
          <span className="text-2xl font-bold text-foreground">
            {category.passed}/{category.total}
          </span>
          <span className="text-sm text-muted-foreground">
            {passRate}% pass rate
          </span>
        </div>
        <WexProgress value={passRate} className="h-2" />
        <div className="flex gap-4 text-sm">
          <span className="text-success flex items-center gap-1">
            <CheckCircle className="h-3 w-3" />
            {category.passed} passed
          </span>
          {category.failed > 0 && (
            <span className="text-destructive flex items-center gap-1">
              <XCircle className="h-3 w-3" />
              {category.failed} failed
            </span>
          )}
        </div>
      </WexCard.Content>
    </WexCard>
  );
}

function FilesList({ files }: { files: CategoryData["files"] }) {
  const sorted = [...files].sort((a, b) => {
    // Failed first, then by name
    if (a.status !== b.status) {
      return a.status === "failed" ? -1 : 1;
    }
    return a.name.localeCompare(b.name);
  });

  return (
    <div className="divide-y divide-border">
      {sorted.map((file) => (
        <div 
          key={file.path} 
          className="py-3 flex items-center justify-between hover:bg-muted/50 px-2 -mx-2 rounded"
        >
          <div className="flex items-center gap-3 min-w-0">
            <StatusBadge status={file.status} />
            <div className="min-w-0">
              <p className="font-mono text-sm truncate">{file.name}</p>
              <p className="text-xs text-muted-foreground">
                {file.passed}/{file.passed + file.failed} tests • {formatDuration(file.duration)}
              </p>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

export default function UnitTestsPage() {
  const testedAt = data._meta?.generatedAt 
    ? new Date(data._meta.generatedAt).toLocaleString()
    : "Unknown";

  return (
    <article>
      <header className="mb-8">
        <h1 className="text-3xl font-display font-bold text-foreground mb-2">
          Unit Test Results
        </h1>
        <p className="text-lg text-muted-foreground">
          Test coverage for WEX components, utilities, and hooks using Vitest + React Testing Library.
        </p>
      </header>

      {/* Summary Stats */}
      <Section title="Test Summary" className="mb-8">
        <div className="flex items-center gap-2 mb-4 text-sm text-muted-foreground">
          <Clock className="h-4 w-4" />
          Last run: {testedAt}
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <WexCard className="text-center py-4">
            <p className="text-3xl font-bold text-foreground">{data.totals.tests}</p>
            <p className="text-sm text-muted-foreground">Total Tests</p>
          </WexCard>
          <WexCard className="text-center py-4">
            <p className="text-3xl font-bold text-success">{data.totals.passed}</p>
            <p className="text-sm text-muted-foreground">Passed</p>
          </WexCard>
          <WexCard className="text-center py-4">
            <p className="text-3xl font-bold text-destructive">{data.totals.failed}</p>
            <p className="text-sm text-muted-foreground">Failed</p>
          </WexCard>
          <WexCard className="text-center py-4">
            <p className="text-3xl font-bold text-foreground">{data.totals.passRate}%</p>
            <p className="text-sm text-muted-foreground">Pass Rate</p>
          </WexCard>
        </div>

        <WexProgress value={data.totals.passRate} className="h-3" />
      </Section>

      {/* Category Breakdown */}
      <Section title="Test Categories" className="mb-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <CategoryCard 
            title="Components" 
            icon={Layers} 
            category={data.categories.components} 
          />
          <CategoryCard 
            title="Utilities" 
            icon={Wrench} 
            category={data.categories.utils} 
          />
          <CategoryCard 
            title="Hooks" 
            icon={RefreshCw} 
            category={data.categories.hooks} 
          />
        </div>
      </Section>

      {/* Test Files */}
      <Section title="Test Files" className="mb-8">
        <WexTabs defaultValue="components" className="w-full">
          <WexTabs.List className="mb-4">
            <WexTabs.Trigger value="components">
              Components ({data.categories.components.files.length})
            </WexTabs.Trigger>
            <WexTabs.Trigger value="utils">
              Utilities ({data.categories.utils.files.length})
            </WexTabs.Trigger>
            <WexTabs.Trigger value="hooks">
              Hooks ({data.categories.hooks.files.length})
            </WexTabs.Trigger>
            {data.failures.length > 0 && (
              <WexTabs.Trigger value="failures" className="text-destructive">
                Failures ({data.failures.length})
              </WexTabs.Trigger>
            )}
          </WexTabs.List>

          <WexTabs.Content value="components">
            <FilesList files={data.categories.components.files} />
          </WexTabs.Content>

          <WexTabs.Content value="utils">
            <FilesList files={data.categories.utils.files} />
          </WexTabs.Content>

          <WexTabs.Content value="hooks">
            <FilesList files={data.categories.hooks.files} />
          </WexTabs.Content>

          {data.failures.length > 0 && (
            <WexTabs.Content value="failures">
              <div className="space-y-4">
                {data.failures.map((failure, i) => (
                  <WexCard key={i} className="border-destructive/30">
                    <WexCard.Header className="pb-2">
                      <div className="flex items-center gap-2">
                        <XCircle className="h-4 w-4 text-destructive" />
                        <WexCard.Title className="text-sm font-mono">
                          {failure.file}
                        </WexCard.Title>
                      </div>
                    </WexCard.Header>
                    <WexCard.Content>
                      <p className="text-sm font-medium mb-2">{failure.test}</p>
                      <p className="text-xs text-muted-foreground font-mono bg-muted p-2 rounded overflow-x-auto">
                        {failure.message}
                      </p>
                    </WexCard.Content>
                  </WexCard>
                ))}
              </div>
            </WexTabs.Content>
          )}
        </WexTabs>
      </Section>

      {/* How to Run */}
      <Section title="How to Run Tests">
        <div className="space-y-4">
          <p className="text-muted-foreground">
            Run unit tests locally using the following commands:
          </p>

          <div className="space-y-3">
            <div>
              <p className="text-sm font-medium mb-1">Run all tests once:</p>
              <CodeBlock code="npm run test:unit" language="bash" />
            </div>

            <div>
              <p className="text-sm font-medium mb-1">Run tests in watch mode:</p>
              <CodeBlock code="npm run test:unit:watch" language="bash" />
            </div>

            <div>
              <p className="text-sm font-medium mb-1">Generate test report:</p>
              <CodeBlock code="npm run test:unit:report" language="bash" />
            </div>
          </div>

          <p className="text-sm text-muted-foreground mt-4">
            Tests are written using <strong>Vitest</strong> with{" "}
            <strong>React Testing Library</strong>. Test files are located in{" "}
            <code className="px-1.5 py-0.5 bg-muted rounded text-xs">tests/</code>.
          </p>
        </div>
      </Section>
    </article>
  );
}

